### ISSUE TITLE
`go test -v` stops working

### ISSUE THREAD

**Issue by wyc** [namsral/flag#10]
Hi, when I use your library instead of the default `flag`, I encounter this error when I try to run tests in verbose mode:

```bash
$ go test -v
flag provided but not defined: -test.v
```

Any quick fix for this?

**Comment by wyc** [comment]
Okay, as a hack, I added this to my global vars:
`var        chatty          = flag.Bool("test.v", false, "verbose: print additional output")`

Taken from here: https://golang.org/src/testing/testing.go#L232

**Comment by wyc** [comment]
I see this issue describing the same thing: https://github.com/namsral/flag/issues/9

Here are steps to reproduce:

(1) Download this gist into its own directory https://gist.github.com/wyc/b6d7dae829e613e5260e4310061161de
(2) Run `go test -v`

**Comment by namsral** [comment]
Thanks for taking the time to describe the problem and write a test.

Please test d922432 in the `testflag` branch for a fix.

**Comment by wyc** [comment]
Hey, thanks for the swift response on this! I really appreciate it. Your solution works perfectly for me.

Added a test here in case you wanted one:
https://github.com/namsral/flag/pull/11

Consider it solved!
