### ISSUE TITLE
Config file parse failure "configuration variable provided but not defined" is not visible to application

### ISSUE THREAD

**Issue by nvx** [namsral/flag#7]
When an invalid command line argument is passes, usage information is printed and the application exists by default as per the default ErrorHandling option along with the message "flag provided but not defined: <name of invalid flag>".

When doing the same thing with a config file passed in via -config however, a similar error is printed "configuration variable provided but not defined", but the application does not exit, nor does there appear to be any way to detect this error within the application either.

**Comment by namsral** [comment]
Yes, this needs to be fixed.

Undefined variables should be handled in configuration files and in prefixed environment variables.

**Comment by namsral** [comment]
Commit #b5bfd14 should fix the issue.
