### ISSUE TITLE
Required environment variables is a regression

### ISSUE THREAD

**Issue by rowland** [namsral/flag#8]
An empty string can be a valid parameter. For example, when connecting to an SMTP or Redis server, empty logins and passwords may mean "Do not use authentication." A recent update forces one to use magical, non-empty values, at least when configuring a program via environment variables, as is common with Dockerized applications.

**Comment by namsral** [comment]
> A recent update forces one to use magical, non-empty values

Update to what, could you elaborate?

**Comment by rowland** [comment]
Looking back further, it appears namsral/flag always considered an empty environment variable an error (https://github.com/namsral/flag/commit/85ddf8100749220191b749c0ef7a95f6494ffc37#diff-1fdeef6cfb1d74886a385d13094d6cbcR862), but only recently (https://github.com/namsral/flag/commit/eb6cc055f3cdae434d691800dddb7251154e3a74) did the errors start getting returned, breaking some of my programs.

I still think an empty string should be a legitimate configuration value.

**Comment by namsral** [comment]
Wether or not an empty string is a valid configuration value is debatable. But one of the project goals is a uniform user experience between the three input methods, which eb6cc05 fixed.

I'm sorry the bug fix broke some of your programs. To fix your issue I could add a new error type `flag.ErrVarUndefined` which can be used to catch undefined variable errors so you can handle accordingly.

Example:

```
if err := flag.CommandLine.Parse(os.Args[1:]); err != nil {
    switch err.(type) {
    case flag.ErrVarUndefined:
        pass
    default:
        panic(err)
    }
}
```

**Comment by rowland** [comment]
An error of a known type (or value) would indeed allow empty parameters to be expressed more naturally, but not if parsing exits on the first error.

**Comment by noonat** [comment]
If you're striving for consistency, an empty string being an error for these cases actually violates that. For a simple example like:

```go
package main

import (
	"fmt"
	"github.com/namsral/flag"
)

func main() {
	var s string
	flag.StringVar(&s, "foo", "", "Test")
	flag.Parse()
	fmt.Println(s)
}
```

It's valid to omit the flag or specify it on the command line:

```go
$ go run main.go
foo is ""
$ go run main.go -foo=
foo is ""
```

But it fails for a config or environment variable:

```go
$ cat config.cfg
foo:
$ go run main.go -config=config.cfg
configuration variable provided but not defined: foo:
Usage of main:
  -config="":
  -foo="": Test
exit status 2

$ FOO= go run main.go
environment variable needs an value: foo
Usage of main:
  -config="":
  -foo="": Test
exit status 2
```

It seems to me that it might be better to allow the parsing in the Set methods for the individual values to raise errors if something is considered invalid for that type, and not do an explicit empty check for environment or config variables.

**Comment by namsral** [comment]
Thanks @noonat for showing me the inconsistency in a code example.

Commit e643283 removes the required configuration and environment variables.
