### ISSUE TITLE
Running go test with any of the standard flags throws an "flag provided but not defined:" error

### ISSUE THREAD

**Issue by domthinks** [namsral/flag#9]
Hi, 

When using the this package and running `go test` with any of the testing package's  [testflags](https://golang.org/src/cmd/go/testflag.go) I get an error. 
For example, running `go test -v` will produce the following :
> flag provided but not defined: -test.v

  The `test.v` is  used to print out verbose output (https://golang.org/src/testing/testing.go). 

`chatty= flag.Bool("test.v", false, "verbose: print additional output")`

Is there any way to make this package aware of other (Go) flags. This will allow the usage of [testflags](https://golang.org/src/cmd/go/testflag.go). 

Thanks
-Dom

**Comment by namsral** [comment]
Could you post a gist with some test code of what you're trying to achieve?

**Comment by domthinks** [comment]
Unfortunately, the project was changed to instead use the built-in environment variables via `os.Setenv`. However, I could try to reproduce the error again by checking out the old version of the code.  

Thank you for your response. 
-Dom

**Comment by namsral** [comment]
I'm closing the issue but will reopen when you have time to reproduce the error, thanks.

**Comment by domthinks** [comment]
@namsral Sounds good.

**Comment by namsral** [comment]
@domthinks Can you confirm 59ceb74 from the testflag branch fixes your issue running `go test -v`?

**Comment by domthinks** [comment]
@namsral I have tested the code in 59ceb746bfc316b3f3ed069c7784f04ba0fc3075 and the -v flag works without any error.

Thanks for following up on this issue. 

Regards, 
-Dom

**Comment by domthinks** [comment]
@namsral I have tested the code in 59ceb746bfc316b3f3ed069c7784f04ba0fc3075 and the -v flag works without any error.

Thanks for following up on this issue. 

Regards, 
-Dom
